### ISSUE TITLE
[spec] Allow both LigatureCaretByPos and LigatureCaretByIndex on the same glyph?

### ISSUE THREAD

**Issue by brawer** [adobe-type-tools/afdko#95] opened 2016-01-07 16:42 UTC
Currently, [section 9.b](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#9.b) of the OpenType Feature File specification does not make it clear whether the same glyph can have both LigatureCaretByPos and LigatureCaretByIndex statements. Should this be allowed? Might be good to clarify the spec.

Example:
```
table GDEF {
     LigatureCaretByPos [c_t c_s]  500;
     LigatureCaretByIndex c_t 5;
} GDEF;
```

**Comment by behdad** [comment] 2016-01-07 17:09
I don't think so; they'll be in conflict.

My guess is that when specified by Index, one is supposed to fetch the position of that point from the glyph outline to encode it in the GDEF table.  Is that what you are doing?

**Comment by readroberts** [comment] 2016-01-07 17:31
I very much appreciate that you are reading the spec so carefully, and finding long-standing major errors. However, since you review is (unfortunately) being so productive, I will wait for you to let me know that you have finished as much as you plan to do, and then I will make all the outstanding changes. Also, please fell free to make them yourself is you want.

**Comment by brawer** [comment] 2016-01-07 18:05
> when specified by Index, one is supposed to fetch the position of that point from the glyph outline to encode it in the GDEF table

No, perhaps the keyword “LigatureCaretByIndex” is a little misleading. The statement builds CaretValue format 2, where the ligature position is specified as contour points. Hinting can move contour points around, so cannot be done at build time.

The current implementation of `makeotf` accepts both LigatureCaretByPos and LigatureCaretByIndex for the same ligature, and makes them CaretValue of format 1 respectively 2. Format 1 comes before 2 in the ordering. The current implementation of fontTools matches `makeotf`.

@readroberts, sure, I’ll gladly send pull requests for the spec.

**Comment by behdad** [comment] 2016-01-07 18:14
> The statement builds CaretValue format 2, where the ligature position is specified as contour points.

Oh interesting.  I never noticed the following discrepancy: in GPOS Anchor Table format 2, which has a contour point index, it still encodes the coordinates as well.  I always assumed that caret values are the same.

**Comment by brawer** [comment] 2016-01-07 20:00
Also, the current spec is silent on whether it’s legal to give multiple `LigatureCaretByPos` or `LigatureCaretByIndex` statements for the same glyph. For example:
```
table GDEF {
    LigatureCaretByPos f_f_f_i 600 200;
    LigatureCaretByPos f_f_f_i 400;
} GDEF;
```

Both `makeotf` and `fontTools` allow this. These implementations collect the caret positions for each glyph and emit them in sorted order:
```
    <LigCaretList>
      <Coverage>
        <Glyph value="f_f_f_i"/>
      </Coverage>
      <!-- LigGlyphCount=1 -->
      <LigGlyph index="0">
        <!-- CaretCount=3 -->
        <CaretValue index="0" Format="1">
          <Coordinate value="200"/>
        </CaretValue>
        <CaretValue index="1" Format="1">
          <Coordinate value="400"/>
        </CaretValue>
        <CaretValue index="2" Format="1">
          <Coordinate value="600"/>
        </CaretValue>
      </LigGlyph>
    </LigCaretList>
```

How about saying the following in the spec?

> The same glyph can be specified in multiple `LigatureCaretByPos`, `LigatureCaretByIndex` and `LigatureCaretByDev` statements. For every glyph, implementations must collect all caret values and emit a merged `LigGlyph` table in `GDEF.LigCaretList`. Implementations may emit a warning if the number of caret values is different from the number of component glyphs (eg., inferred from the glyph name).

Since the order can change at runtime anyway (because hinting affects caret values in format 2), there probably is not much point in mandating any particular sorting order.

Thoughts?

**Comment by behdad** [comment] 2016-01-08 00:14
I suggest disallowing multiple declarations for the same glyph.  Warn and only accept the last one, or first one.

> Since the order can change at runtime anyway (because hinting affects caret values in format 2), there probably is not much point in mandating any particular sorting order.

Sorting order *is* important.  That's what specifies which ligature component a particular point reflects.

**Comment by brawer** [comment] 2016-01-08 07:56
@readroberts, what do you think? makeotf currently allows multiple statements for the same glyph, and merges them silently together. Unless the same caret value gets supplied multiple times, in which case it emits a warning. Personally I’ve no opinions either way — I’d just like to have a spec that defines how an implementation should behave.

**Comment by readroberts** [comment] 2016-04-13 16:42
Fixed in feature file spec 1.19. ALlow only one LigatureCaret statement per glyph.

**Closed by readroberts** 2016-04-13 16:42 UTC

**Comment by khaledhosny** [comment] 2019-09-26 14:34
Though the spec was changed, `makeotfexe` still allows multiple `LigatureCaret` rules and silently uses the last one without issuing an error or a warning, is this the expected behavior?

**Comment by khaledhosny** [comment] 2019-09-26 14:36
Sorry, it uses the first and ignores the rest, as per #155.
