### ISSUE TITLE
Is there any plan to make the features file support non-ASCII chars?

### ISSUE THREAD

**Issue by LIXiangChen** [adobe-type-tools/afdko#696] opened 2018-12-15 12:01 UTC
I found that `FontMenuNameDB` file now supports non-ASCII chars, which is very useful, however the `features` file is still not supported (Mainly used to set the `name` table).

**Comment by miguelsousa** [comment] 2018-12-15 19:39
Duplicate of #165

**Closed by miguelsousa** 2018-12-15 19:39 UTC
