### ISSUE TITLE
Reusing components / subroutinezation is missing?

### ISSUE THREAD

**Issue by dy** [adobe-type-tools/afdko#1319] opened 2021-02-28 17:08 UTC
Trying to implement composite glyphs in [wavefont](https://a-vis.github.io/wavefont) as reusing smaller glyphs with overlay:
![image](https://user-images.githubusercontent.com/300067/109426380-798c1180-79bb-11eb-9bca-d1a6ce777fd1.png)

Running the following commands to build variable OTF:
```
buildmasterotfs --mkot -r,-S,-omitMacNames -d masters/wavefont.designspace
buildcff2vf -c -k -d masters/wavefont.designspace -o ./font/wavefont.otf
```

Resulting OTF font file size increases from _35kb_ for simple glyphs to _48kb_ for composed glyphs.
To compare, TTF font size reduces from _35kb_ for simple glyphs to _27kb_ for composed glyphs, due to components reuse.

Inspecting masters shows that OTF doesn't use components, unlike TTF, but instead flattens glyph shapes:
![image](https://user-images.githubusercontent.com/300067/109426577-69c0fd00-79bc-11eb-9f9d-813610fce2bb.png)

With TTF the upper/lower halves reuse `_50` glyph:
![image](https://user-images.githubusercontent.com/300067/109426799-6f6b1280-79bd-11eb-9ba3-38e0eb3a3622.png)

I expected subroutinization to be on-par with TTF components, but it seems it's missing or not as efficient in terms of reducing font size.

Is there a special option to force subroutinization/ehnance OTF build, or any sort of components-like technique of reusing glyphs, or that file size tax is unavoidable?

**Comment by benkiel** [comment] 2021-02-28 18:24
@dy are you running `makeOTF` with the `-r` (release mode) flag turned on? That turns on the subroutinization. You can also  use `-S` to turn it on if you don't want to set release mode. In CFF OTFs there aren't components, and things are flattened. Depending on the design, the subroutinization will be on par with TTF OTF components, smaller, or sometimes larger: it depends on if flattening components and removing overlap makes new shapes or if there are lots of shapes that can be compacted easily. Someone from Adobe will likely have a more detailed answer than that.

**Comment by dy** [comment] 2021-03-01 02:13
`-r` without `-S` doesn't seem to make much difference. Just curious if that particular case can be expected to be more optimal, or the result is expected.

**Comment by josh-hadley** [comment] 2021-03-01 17:19
CFF subroutinization does not work the same way as TTF composite glyphs. They're similar ideas (pattern replacement) but CFF subroutinization works on the sub-path level (curve/line segments that make up a larger contour) whereas TTF is typically complete contours or groups of contours (i.e. if you have glyphs`Aacute`, `A`, and `acute`, you could potentially build `Aacute` with a recipe of something like "`A` + `acute` moved up and over a little"). TTF composite glyphs can also make use of a [2x2 transformation matrix](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf#composite-glyph-description) to enable stretching/slanting/rotating components.

As @benkiel pointed out, the design will dictate the savings. Sometimes subroutinization yields larger savings, sometimes componentization does.

Additionally, as noted in [this thread](https://github.com/adobe-type-tools/cffsubr/issues/9), the order of glyph analysis for subroutinization can impact the size efficiency. Both `makeotf` and `tx` support subroutinization, but they can yield different results because the glyphs get analyzed in a different order. So for fun, you might try [subroutinizing with `tx`](https://github.com/adobe-type-tools/afdko/wiki/How-To#cff) and see if it makes any difference.

**Comment by miguelsousa** [comment] 2021-03-01 18:09
@dy `buildcff2vf` doesn't do any subroutinization; it needs to be done as a separate step afterwards. See [this example](https://github.com/adobe-fonts/source-serif/blob/main/buildVFs.sh#L26-L31).

**Comment by cjchapman** [comment] 2021-03-01 18:17
There's also an example in the AFDKO wiki:
[How to subroutinize a CFF or CFF2 font](https://github.com/adobe-type-tools/afdko/wiki/How-To#how-to-subroutinize-a-cff-or-cff2-font)

**Comment by josh-hadley** [comment] 2021-03-03 23:57
@dy I think your question is answered, so I'm going to close this issue. Please re-open if you have remaining concerns or questions related to this.

**Closed by josh-hadley** 2021-03-03 23:57 UTC

**Comment by dy** [comment] 2021-03-04 00:15
Sorry for the delay, was hoping to test out with [linefont](https://a-vis.github.io/linefont/).
After performing `cp ./font/wavefont.otf ./font/wavefont.min.otf && tx -cff2 +S +b ./font/wavefont.otf > ./font/table.CFF2 && sfntedit -a CFF2=./font/table.CFF2 ./font/wavefont.min.otf` from [howto example](https://github.com/adobe-type-tools/afdko/wiki/How-To#cff2) the font loses all characters. Is there some info missing, like stats?

[before-after-subr.zip](https://github.com/adobe-type-tools/afdko/files/6079943/before-after-subr.zip)

**Comment by josh-hadley** [comment] 2021-03-04 00:31
@dy I'm unable to reproduce that problem here. I agree that the `wavefont.min.otf` that you attached is not correct; it seems that something became corrupted:

```bash
$ tx -dump -1 wavefont.min.otf 
tx: --- wavefont.min.otf
tx: (cfr) bad INDEX header
```
When I run those commands here, I get different output (attached).

[wavefont.min.otf.zip](https://github.com/adobe-type-tools/afdko/files/6079991/wavefont.min.otf.zip)
