### ISSUE TITLE
[makeotf] cannot find PS name w/ unrelated lib.plist entry

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#701] opened 2018-12-18 14:32 UTC
`makeotf` v2.6.0 won’t be able to find a UFO3’s PostScript name if the `lib.plist` file contains a reference to the ScaleFast extension, like this:

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.loicsander.scaleFast</key>
    <dict>
      <key>guides</key>
      <array/>
      <key>presets</key>
      <dict/>
    </dict>
  </dict>
</plist>
```

`makeotf` fails with this message:
```
$ makeotf -f PSnameSerifText-Bold.ufo/
makeotf [Warning] Could not find default features file at 'None'. Font will be built without any layout features.
makeotf [Error] Could not find FontName (a.k.a. PostScript name) in FontDict of file '/Users/fgriessh/Desktop/psname_test/PSnameSerifText-Bold.ufo'
```

If the key is removed from the lib, the UFO will build without issues.
Example UFO attached. Another issue found thanks to the example files submitted by @rbmntjs.

[PSnameSerifText-Bold.ufo.zip](https://github.com/adobe-type-tools/afdko/files/2690922/PSnameSerifText-Bold.ufo.zip)

**Comment by rbmntjs** [comment] 2018-12-18 20:05
Is this just caused by the self-closing XML? I think I’ve actually encountered this issue before, but I totally forgot about it.

**Comment by frankrolf** [comment] 2018-12-18 20:13
Perhaps? But even if it is, it should not result in the above.
Thanks for the pointer though, it’s something we can investigate.

**Comment by frankrolf** [comment] 2018-12-19 15:06
It’s the self-closing `<dict/>`.
If I change that into `<dict></dict>`, it works.
I guess this issue underlines the importance of replacing our home-grown XML parser, as already planned here: https://github.com/adobe-type-tools/afdko/issues/475#issue-340456426

**Comment by miguelsousa** [comment] 2019-02-07 17:50
The bug is in the UFO-reading code of `tx`. Currently working on a fix.

**Closed** 2019-02-08 00:10 UTC
Labels: c-tools, py-tools, tx, ufo3
