### ISSUE TITLE
[makeotf] consume `tx` stderr

### ISSUE THREAD

**Issue by benkiel** [adobe-type-tools/afdko#1074] opened 2020-01-04 17:47 UTC
(this is a weird edge case, so feel free to close)

When running `makeotf` from inside another script and redirecting stdout and stderr to a file, the `tx` errors when converting a format https://github.com/adobe-type-tools/afdko/blob/d0ccb710d31688ec76538bab18ceca80813ea969/python/afdko/makeotf.py#L2019 are still printed to stderr (in my case, complaints about underline thickness). I think that if that line was change to consume stderr (as in #751) this would go away. (think as i've not had time to test that change)

**Comment by josh-hadley** [comment] 2020-01-07 00:21
Out of curiosity: did this ever work the way you wanted it to (i.e. in older versions of AFDKO)? The reason I ask is, we've been tinkering with that `run_shell_command` routine to work around some intermittent issues with our automated testing. Maybe we need to give it some more attention. Can you attach (or describe) a simple test case that reproduces this?

**Comment by miguelsousa** [comment] 2020-01-07 02:11
@josh-hadley before 5f6f5752965263a2a712b126802cc255d737411f the messages from **tx** and other commands were always discarded (see all the `2>&1` tokens thruout). I understand Ben's request but I don't think we should go back to muting everything by default. Perhaps a workable solution is to enabling switching them off by piggy-backing on an existing **makeotf** option.

**Comment by benkiel** [comment] 2020-01-07 04:56
@josh-hadley Yes, I can put together a sample script. For what I was doing, I've gone back to subprocess like so:

```python
args = ["makeotf", "-f", file, "-o", outputPath, "-r", "-nshw"]
run = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, universal_newlines=True)
with open(path, "w") as f:
    f.write(run.stdout)
```

which consumes the even the tx output from makeotf when making a TTF.

Previously I was doing:
```python
from contextlib import redirect_stdout, redirect_stderr
args = ["-f", file, "-o", outputPath, "-r", "-nshw"]
with open(os.path.join(outputPath, f"makeotf_output.txt"), "a") as f:
    with redirect_stdout(f), redirect_stderr(f):
        makeOTFParams = makeotf.MakeOTFParams()
        makeotf.getOptions(makeOTFParams, args)
        makeotf.setMissingParams(makeOTFParams)
        makeotf.setOptionsFromFontInfo(makeOTFParams)

        makeotf.runMakeOTF(makeOTFParams)
```
That wouldn't catch the output from `tx` when it was run to convert the TTF for making a TTF.

Again, I don't think this is a big issue, and should likely be closed. Subprocess is likely the better way to run this, not calling it directly in another script.

**Comment by josh-hadley** [comment] 2020-01-07 17:21
Closing, per discussion.

**Closed by josh-hadley** 2020-01-07 17:21 UTC
