### ISSUE TITLE
buildcff2vf: errors on validating STAT axis values

### ISSUE THREAD

**Issue by dy** [adobe-type-tools/afdko#1308] opened 2021-02-18 02:31 UTC
Trying to build variable OTF in [wavefont](https://github.com/audio-lab/wavefont/blob/master/package.json#L13).

```sh
buildcff2vf -k -d masters/wavefont.designspace -o ./font/wavefont.otf

Reading source fonts...
Building variable OTF (CFF2) font...
Validating STAT axis values...
Traceback (most recent call last):
  File "c:\users\dfcre\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dfcre\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dfcre\AppData\Roaming\Python\Python39\Scripts\buildcff2vf.exe\__main__.py", line 7, in <module>
  File "C:\Users\dfcre\AppData\Roaming\Python\Python39\site-packages\afdko\buildcff2vf.py", line 590, in main
    validate_stat_values(varFont)
  File "C:\Users\dfcre\AppData\Roaming\Python\Python39\site-packages\afdko\buildcff2vf.py", line 409, in validate_stat_values
    if hasattr(stat.table.AxisValueArray, "AxisValue"):
  File "C:\Users\dfcre\AppData\Roaming\Python\Python39\site-packages\fontTools\ttLib\tables\otBase.py", line 555, in __getattr__
    raise AttributeError(attr)
AttributeError: AxisValueArray
```

Interestingly in [variable font prototype](https://github.com/adobe-fonts/adobe-variable-font-prototype) everything compiles fine.

Can you point out possible whereabouts of error? Tried stubbing STAT.fea file - it didn't help, also `fontmake` errors that stat table is not supported.

**Comment by punchcutter** [comment] 2021-02-18 02:55
This was addressed in https://github.com/adobe-type-tools/afdko/pull/1283

**Comment by punchcutter** [comment] 2021-02-18 02:56
For the other error in `fontmake` that's because `STAT` isn't supported yet in fontTools feaLib. We have a new update for that almost ready so hopefully it will get in there soon.

**Comment by punchcutter** [comment] 2021-02-18 03:00
You can try again with the latest pre-release by installing it with `pip install --pre afdko==3.6.2a1` and you shouldn't run into this problem.

**Comment by dy** [comment] 2021-02-18 16:07
@punchcutter build was successful, but resulting font is malformed:
![image](https://user-images.githubusercontent.com/300067/108385280-82216280-71d9-11eb-9147-4f12158b060e.png)
Fontforge can't open it too.

**Comment by josh-hadley** [comment] 2021-02-18 19:58
@dy the ot-sanitizer failure results because the output `wavefont.otf` contains only a single cmap subtable with platformID 1, encodingID 0, and format 6 which is not in the [set of cmap subtables that ot-sanitizer supports](https://github.com/khaledhosny/ots/blob/6e9a697bd9a76475d2d947fb1a371e8f7a6edb32/src/cmap.cc#L856-L859). It's not clear to me which step of the process is causing the font to get generated with that; normally I'd expect to see a platformID 3, encodingID 1, format 4 subtable at least.

**Comment by frankrolf** [comment] 2021-02-18 20:50
I would love to help here, but it seems like the UFO data provided at https://github.com/audio-lab/wavefont/tree/master/masters is incomplete. Can you check if you have all the .glif files checked in?
Thanks!
![image](https://user-images.githubusercontent.com/2049645/108419775-3dc2b080-7233-11eb-83fc-9dbe6619d4ac.png)

**Comment by frankrolf** [comment] 2021-02-18 21:06
Never mind, @josh-hadley helped me figure it out.

**Comment by dy** [comment] 2021-02-18 21:09
> Can you check if you have all the .glif files checked in?

Sorry I should've elaborated building in readme. I run `npm run build-values-1-0` before building the font.

**Comment by frankrolf** [comment] 2021-02-18 21:17
No worries, I figured it out! :-)
The problem is that you did not use a GlyphOrderAndAliasDB file. The GlyphOrderAndAliasDB (and `makeotf`’s `-r` option) is responsible for mapping code points to the output font. Place the attached file (unzipped) into your masters directory, any you’ll get a proper cmap.

[GlyphOrderAndAliasDB.zip](https://github.com/adobe-type-tools/afdko/files/6005936/GlyphOrderAndAliasDB.zip)

**Comment by frankrolf** [comment] 2021-02-18 21:24
`buildmasterotfs` just calls `makeotf` with the `-r` (release mode) option:
https://github.com/adobe-type-tools/afdko/blob/develop/python/afdko/buildmasterotfs.py#L102-L103

The `-r` option reads the GlyphOrderAndAliasDB file, and in turn assigns the code points and glyph order to the font binary.

**Comment by frankrolf** [comment] 2021-02-18 21:30
I am realizing that the GlyphOrderAndAliasDB I attached may be incomplete - there is a glyph with many code points, which would need to be specified in the 3rd column, like this: https://github.com/adobe-fonts/source-serif/blob/main/Roman/GlyphOrderAndAliasDB#L2

**Closed** 2021-02-18 21:29 UTC

**Comment by josh-hadley** [comment] 2021-02-18 21:38
@dy one suggestion I have is to consider using Private Use Area (PUA) Unicode values rather than existing assigned Unicodes (e.g. [U+0100](https://www.compart.com/en/unicode/U+0100) which is already "Latin Capital Letter A with Macron"). Text layout engines and other higher-order protocols might make assumptions about properties of characters based on their Unicode values.

**Comment by dy** [comment] 2021-02-18 23:04
Text manipulations and unicode rules were taken into consideration for selecting range.
Generally correct would be using private area, but letters class enables text manipulation capabilities, such as regex word boundary detection, word select (double click, <kbd>Ctrl</kbd> + <kbd>←</kbd>/<kbd>→</kbd>) and possibly others. That is especially handy for the case of editing sound - double click selects a fragment surrounded by silence.
I think it's a good idea to copy to private area for general/extended use indeed, thank you for the hint.

**Comment by dy** [comment] 2021-02-18 23:16
@frankrolf interestingly, there seems to be a limit on max number of aliases in GlyphOrderAndAliasDB.
This has no effect:
```
.notdef	.notdef
_ _ uni0020,uni0021,uni0022,uni0023,uni0024,uni0025,uni0026,uni0027,uni0028,uni0029,uni002a,uni002b,uni002c,uni002d,uni002e,uni002f,uni0030,uni0031,uni0032,uni0033,uni0034,uni0035,uni0036,uni0037,uni0038,uni0039,uni003a,uni003b,uni003c,uni003d,uni003e,uni003f,uni0040,uni0041,uni0042,uni0043,uni0044,uni0045,uni0046,uni0047,uni0048,uni0049,uni004a,uni004b,uni004c,uni004d,uni004e,uni004f,uni0050,uni0051,uni0052,uni0053,uni0054,uni0055,uni0056,uni0057,uni0058,uni0059,uni005a,uni005b,uni005c,uni005d,uni005e,uni005f,uni0060,uni0061,uni0062,uni0063,uni0064,uni0065,uni0066,uni0067,uni0068,uni0069,uni006a,uni006b,uni006c,uni006d,uni006e,uni006f,uni0070,uni0071,uni0072,uni0073,uni0074,uni0075,uni0076,uni0077,uni0078,uni0079,uni007a,uni007b,uni007c,uni007d,uni007e,uni007f
```
but this works:

```
.notdef	.notdef
_ _ uni0020,uni0021,uni0022,uni0023,uni0024,uni0025,uni0026,uni0027
```

**Comment by josh-hadley** [comment] 2021-02-22 21:22
> interestingly, there seems to be a limit on max number of aliases in GlyphOrderAndAliasDB

The limitation is actually on the length of the 3rd column contents, not the number of aliases. Support for multiple mappings was an add-on (initially it was only a single mapping) and apparently no one foresaw a need for a case like yours where you have many re-mappings (and a long string describing them).
I think we can extend the limit on the 3rd column to accommodate more. If we extend the limit to, say, 1000 characters, your case should work (with a little extra room to spare).
