### ISSUE TITLE
[mergefonts] warning messages are accumulated

### ISSUE THREAD

**Issue by nozoka** [adobe-type-tools/afdko#635] opened 2018-10-03 14:29 UTC
In mergefonts, warning messages are accumulated through a source font file (type1) because once warning message is added in cstrCtx->warning[type] in cffwrite_t2cstr.c, it is not cleared until the end of the source font. This blindfolds a real warning message per glyph.

I suggest that printFinalWarn(g) be moved or copied from cfwEndFont() in cffwrite.c to the end of glyphEnd() in cffwrite_t2cstr.c.

**Comment by readroberts** [comment] 2018-10-03 17:20
Thank you, this is very useful.

**Comment by miguelsousa** [comment] 2018-10-11 15:31
Neither moving nor copying the `printFinalWarn(g);` line produces the desired results.

Here's a test case: `mergefonts newfont font.pfa font.cff`
[bug635.zip](https://github.com/adobe-type-tools/afdko/files/2469566/bug635.zip)

The output of the command above is:
```
mergefonts: --- font.pfa
mergefonts: (cfw) unhinted <.notdef>
mergefonts: (cfw) unhinted <adieresis>
mergefonts: (cfw) unhinted <N>
mergefonts: (cfw) unhinted <uni1E6D>
mergefonts: (cfw) unhinted <ycircumflex>
mergefonts: --- font.cff
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <.notdef>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <B>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <G>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <N>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <bracketright>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni2009>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni028C>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <egrave.sups>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0326>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0300.g>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <two.onum>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0289>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <infinity>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <b.sups>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni012C>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <nine.subs>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <racute>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni030A.c>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <emacron>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <lcaron.a>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <arrowup>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <triagdn>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0284>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <Dcaron>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni03060303>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <Wdieresis>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni2713>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni1EE2>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni2155>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <a.sups>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni03130303>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni1EE8>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni014A.a>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni028F>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni03060301>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0278>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni1E34>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni03060300.c>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <zero.subs>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <Aogonek.d>
mergefonts: (cfw) There are 45 additional reports of 'unhinted'.

mergefonts: (cfw) There are 45 additional reports of 'glyph skipped - same name, different charstring as glyph in font'.

```
This output contains two issues:

1. The lines containing the words **additional reports** should appear right after their respective group.
2. There should only be five **glyph skipped - duplicate of glyph** lines; the remaining should be replaced by an **additional reports** line.

**Comment by nozoka** [comment] 2018-10-11 18:10
I realized from your comment that the array of cstrCtx->warning is intended to hold warning messages throughout a source font.

I sent a pull request to add a new member in struct cstrCtx_ to hold warning messages per glyph only.

**Comment by miguelsousa** [comment] 2018-10-11 21:06
@nozoka thanks for the patch, but the changes are still not producing what I would consider the correct output. With you patch, the output for the test case I posted above changed to this,
```
mergefonts: --- font.pfa
mergefonts: (cfw) unhinted <.notdef>
mergefonts: (cfw) unhinted <adieresis>
mergefonts: (cfw) unhinted <N>
mergefonts: (cfw) unhinted <uni1E6D>
mergefonts: (cfw) unhinted <ycircumflex>
mergefonts: --- font.cff
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <.notdef>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <B>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <G>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <N>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <bracketright>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni2009>
mergefonts: (cfw) There are 45 additional reports of 'unhinted'.

mergefonts: (cfw) There are 45 additional reports of 'glyph skipped - same name, different charstring as glyph in font'.

```
whereas I think the correct output should be this,
```
mergefonts: --- font.pfa
mergefonts: (cfw) unhinted <.notdef>
mergefonts: (cfw) unhinted <adieresis>
mergefonts: (cfw) unhinted <N>
mergefonts: (cfw) unhinted <uni1E6D>
mergefonts: (cfw) unhinted <ycircumflex>
mergefonts: (cfw) There are 45 additional reports of 'unhinted'.
mergefonts: --- font.cff
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <.notdef>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <B>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <G>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <N>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <bracketright>
mergefonts: (cfw) There are 45 additional reports of 'glyph skipped - same name, different charstring as glyph in font'.
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni2009>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni028C>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <egrave.sups>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0326>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0300.g>
mergefonts: (cfw) There are 30 additional reports of 'glyph skipped - duplicate of glyph in font'.
```

If you would like to take another crack at your patch, leave PR #646 open and just push (or force-push) a new commit to your `nozoka:develop` branch. Thanks.

**Comment by nozoka** [comment] 2018-10-11 22:57
Apparently, in this test case, even without my patch, the output is not correct. I tried with the unpatched mergeFonts:
```
>mergefonts newfont font.pfa font.cff
mergefonts: --- font.pfa
mergefonts: (cfw) unhinted <.notdef>
mergefonts: (cfw) unhinted <adieresis>
mergefonts: (cfw) unhinted <N>
mergefonts: (cfw) unhinted <uni1E6D>
mergefonts: (cfw) unhinted <ycircumflex>
mergefonts: --- font.cff
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <.notdef>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <B>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <G>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <N>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <bracketright>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni2009>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni028C>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <egrave.sups>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0326>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0300.g>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <two.onum>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0289>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <infinity>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <b.sups>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni012C>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <nine.subs>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <racute>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni030A.c>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <emacron>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <lcaron.a>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <arrowup>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <triagdn>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0284>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <Dcaron>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni03060303>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <Wdieresis>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni2713>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni1EE2>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni2155>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <a.sups>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni03130303>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni1EE8>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni014A.a>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni028F>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni03060301>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni0278>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni1E34>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <uni03060300.c>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <zero.subs>
mergefonts: (cfw) glyph skipped - duplicate of glyph in font <Aogonek.d>
mergefonts: (cfw) There are 45 additional reports of 'unhinted'.

mergefonts: (cfw) There are 45 additional reports of 'glyph skipped - same name, different charstring as glyph in font'.
```

My patch in fact does not change the timing of calling printFinalWarn() that outputs "additional reports" for a whole font nor clear h->warning[i]. So, it seems that there is a different problem from what I struggle.

[rotated.zip](https://github.com/adobe-type-tools/afdko/files/2470911/rotated.zip)
What I would like to fix is the following case: rotated.ps in the attached rotated.zip is created by rotatefont with https://github.com/adobe-fonts/source-han-serif/blob/master/Light/cidfont.ps.JP and my additional glyphs. Although CIDs in rotated.ps do not overlap with ones in cidfont.ps.JP, "mergeFonts newfont cidfont.ps.JP rotated.ps" outputs the following warnings:

```
mergefonts: --- cidfont.ps.JP
mergefonts: (cfw) unused hints <cid-13340>
mergefonts: (cfw) unused hints <cid-16961>
mergefonts: (cfw) unused hints <cid-16963>
Adding font dict 0 from cidfont.ps.JP.
Adding font dict 1 from cidfont.ps.JP.
Adding font dict 2 from cidfont.ps.JP.
Adding font dict 3 from cidfont.ps.JP.
Adding font dict 4 from cidfont.ps.JP.
Adding font dict 5 from cidfont.ps.JP.
Adding font dict 6 from cidfont.ps.JP.
Adding font dict 7 from cidfont.ps.JP.
Adding font dict 8 from cidfont.ps.JP.
Adding font dict 9 from cidfont.ps.JP.
Adding font dict 10 from cidfont.ps.JP.
Adding font dict 11 from cidfont.ps.JP.
Adding font dict 12 from cidfont.ps.JP.
Adding font dict 13 from cidfont.ps.JP.
Adding font dict 14 from cidfont.ps.JP.
Adding font dict 15 from cidfont.ps.JP.
Adding font dict 16 from cidfont.ps.JP.
Adding font dict 17 from cidfont.ps.JP.
mergefonts: --- rotated.ps
mergefonts: (cfw) unused hints <cid-0>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-0>
mergefonts: (cfw) unused hints <cid-48456>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48456>
mergefonts: (cfw) unused hints <cid-48483>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48483>
mergefonts: (cfw) unused hints <cid-48505>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48505>
mergefonts: (cfw) unused hints <cid-48536>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48536>
mergefonts: (cfw) unused hints <cid-48556>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48556>
mergefonts: (cfw) unused hints <cid-48572>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48572>
mergefonts: (cfw) unused hints <cid-48573>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48573>
mergefonts: (cfw) unused hints <cid-48574>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48574>
mergefonts: (cfw) unused hints <cid-48575>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48575>
mergefonts: (cfw) unused hints <cid-48576>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48576>
mergefonts: (cfw) unused hints <cid-48577>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48577>
mergefonts: (cfw) unused hints <cid-48634>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48634>
mergefonts: (cfw) unused hints <cid-48636>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48636>
mergefonts: (cfw) unused hints <cid-48669>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48669>
mergefonts: (cfw) unused hints <cid-48691>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48691>
mergefonts: (cfw) unused hints <cid-48693>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48693>
mergefonts: (cfw) unused hints <cid-48695>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48695>
mergefonts: (cfw) unused hints <cid-48697>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48697>
mergefonts: (cfw) unused hints <cid-48699>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48699>
mergefonts: (cfw) unused hints <cid-48701>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48701>
mergefonts: (cfw) unused hints <cid-48703>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48703>
mergefonts: (cfw) unused hints <cid-48705>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48705>
mergefonts: (cfw) unused hints <cid-48707>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48707>
mergefonts: (cfw) unused hints <cid-48709>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48709>
mergefonts: (cfw) unused hints <cid-48711>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48711>
mergefonts: (cfw) unused hints <cid-48713>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48713>
mergefonts: (cfw) unused hints <cid-48881>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48881>
mergefonts: (cfw) unused hints <cid-48954>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48954>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-48957>
mergefonts: (cfw) unused hints <cid-48957>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48957>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-48958>
mergefonts: (cfw) unused hints <cid-48958>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48958>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-48968>
mergefonts: (cfw) unused hints <cid-48968>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48968>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-48990>
mergefonts: (cfw) unused hints <cid-48990>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48990>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-48992>
mergefonts: (cfw) unused hints <cid-48992>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48992>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-48996>
mergefonts: (cfw) unused hints <cid-48996>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-48996>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49002>
mergefonts: (cfw) unused hints <cid-49002>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49002>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49003>
mergefonts: (cfw) unused hints <cid-49003>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49003>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49010>
mergefonts: (cfw) unused hints <cid-49010>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49010>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49011>
mergefonts: (cfw) unused hints <cid-49011>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49011>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49029>
mergefonts: (cfw) unused hints <cid-49029>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49029>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49114>
mergefonts: (cfw) unused hints <cid-49114>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49114>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49115>
mergefonts: (cfw) unused hints <cid-49115>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49115>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49139>
mergefonts: (cfw) unused hints <cid-49139>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49139>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49149>
mergefonts: (cfw) unused hints <cid-49149>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49149>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49160>
mergefonts: (cfw) unused hints <cid-49160>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49160>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49169>
mergefonts: (cfw) unused hints <cid-49169>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49169>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49249>
mergefonts: (cfw) unused hints <cid-49249>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49249>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49275>
mergefonts: (cfw) unused hints <cid-49275>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49275>
mergefonts: (cfw) all hintsubs removed (fixupmap enabled) <cid-49276>
mergefonts: (cfw) unused hints <cid-49276>
mergefonts: (cfw) glyph skipped - same name, different charstring as glyph in font <cid-49276>
mergefonts: (cfw) There are 100 additional reports of 'duplicate hintsubs (discarded)'.
```

The CID range 48450-49282 is not used in cidfont.ps.JP but exists only in rotated.ps, however, mergeFonts reports "glyph skipped - same name, different charstring as glyph in font" for cid-48456 and the following. This message is set for cid-0 and is carried until the end of rotated.ps. I would like to fix this.

**Comment by miguelsousa** [comment] 2018-10-12 01:41
@nozoka understood. I'll have another look at this later. Thanks for the test case.

**Closed** 2018-10-12 18:22 UTC
Labels: c-tools
