### ISSUE TITLE
ImportErrors all around

### ISSUE THREAD

**Issue by rbmntjs** [adobe-type-tools/afdko#204] opened 2017-11-08 14:02 UTC
I’ve performed clean installs, including using `virtualenv` and having cleaned up my `$PATH`, but I’m still getting countless errors. makeOTF returns one thing (a), and when I try to build new fonttools, I get another (b). What am I missing here? I’m on macOS High Sierra, and sure, I know permissions often get nudged out of place, but the tools don’t return any rights errors as far as I can tell.

a: makeOTF can’t find things that `pip` insists are already there:
```
Traceback (most recent call last):
  File "[…]/bin/FDK/Tools/osx/../SharedData/FDKScripts/MakeOTF.py", line 400, in <module>
    from fontTools.ttLib.standardGlyphOrder import standardGlyphOrder as kStdNames
ImportError: No module named fontTools.ttLib.standardGlyphOrder
```

b: installing clean `fonttools` fails:
```
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from setuptools import setup, find_packages, Command
ImportError: No module named setuptools
```
Attempting to `pip install` it tells me I’m barking up the wrong tree:
```
Requirement already up-to-date: setuptools in ./fonttools-venv/lib/python2.7/site-packages
```

**Comment by rbmntjs** [comment] 2017-11-09 10:59
So here’s where I’m at: I installed it from Github, built my own Python, AFDKOPython, following the specifications, and weirdly the `site-packages` folder is entirely empty. That explains why it doesn’t even know of `setuptools`, I suppose. Is this… typical? I followed the instructions to get to this point – has something changed with High Sierra? I mean, it sure looks like it’s a (AFDKO)Python problem, but I don’t know where the fix might be.

**Comment by readroberts** [comment] 2017-11-09 16:52
Hi Robin;

The issue is that the modules were being installed into the  wrong python, the system Python interpreter rather than the AFDKO interpreter. If you just us 'pip' or 'easy_install', you get a version that installs into the default system Python. Probably the easiest thing for you to do is to actually edit the AFDKO so that it will use the system Python. You can do this by editing FDK/Tools/osx/setFDKPaths, and change the line '"AFDKO_Python="${cmdDirPath}"/Python/Current/bin/python' to point the system python program. Alternatively, you can download each module, cd to the root directory, and run "<python> setup.py install" using the AFDKO Python. You well need to install the setuptools module first.

**Comment by frankrolf** [comment] 2018-03-19 20:26
This should be fixed by @cchapman’s work on the `pip` installer. Can this be closed, @rbmntjs?

**Closed** 2018-04-19 23:43 UTC
