### ISSUE TITLE
makeotf runpy.py error

### ISSUE THREAD

**Issue by astype** [adobe-type-tools/afdko#1220] opened 2020-09-03 08:45 UTC
Windows 10 (10.0.18363) 64bit
Phyton 3.7.9,
Last working makeotf version 2.5.65599

I update the fdk with pip and after the update I can't compile any of my projects.

Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\makeotf.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\afdko\makeotf.py", line 2768, in main
    setMissingParams(makeOTFParams)
  File "c:\python37\lib\site-packages\afdko\makeotf.py", line 1887, in setMissingParams
    if not psname_in_fmndb(ps_name, fmndb_path):
  File "c:\python37\lib\site-packages\afdko\makeotf.py", line 1787, in psname_in_fmndb
    fmndb_lst = fp.readlines()
  File "c:\python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 584: invalid continuation byte

Did you have a clue? Thank you for your help.

Andreas

**Comment by frankrolf** [comment] 2020-09-03 10:49
This looks like a non-ASCII character is in the FontMenuNameDB?

**Comment by astype** [comment] 2020-09-03 12:13
It's an all my projects - and they worked for years till now.

**Comment by frankrolf** [comment] 2020-09-03 12:16
Maybe the validation got stricter? I don’t think it’s allowed to have non-ASCII characters in font names.
Can you share the FontMenuNameDB?

**Comment by astype** [comment] 2020-09-03 12:29
You are right, the FontMenuNameDB is more strict now. I have the same head in each file containing some comments in German.

; max länge 31 zeichen mac
; ps länge 29 zeichen / weniger wichtig

In this case the letter ä causes the failure. But I'm wondering why this strict issue now applies to comments too now. 

But it's ok, I can work around it! 

Thank you for your fast help, Frank.

**Comment by frankrolf** [comment] 2020-09-03 12:43
Ha that’s weird – comments should not need to be ASCII. Thanks for the report, I hope there’s something that can be done about it.

**Comment by cjchapman** [comment] 2020-09-03 15:19
Looking at the trace, I think the problem is that the file is not using the UTF-8 encoding.  I'm guessing it is in the Windows 1252 code page encoding.  The `ä` character is stored as a pair of bytes (0xc3, 0xA4) in UTF-8, rather than as a single byte (0xE4).

**Comment by miguelsousa** [comment] 2020-09-03 16:36
> ; max länge 31 zeichen mac
> ; ps länge 29 zeichen / weniger wichtig

Line comments should start with the `#` symbol.
Is that what the file has Andreas?

**Comment by astype** [comment] 2020-09-03 17:21
No, it's ; - In the past this symbol ; was a comment sign in the FontMenuNameDB. But I since it's a silly thing I can change it. - No problem.

**Comment by cjchapman** [comment] 2020-09-03 17:39
@astype Regarding the UTF-8 encoding (vs. CP1252 encoding) that I mentioned above -- there is a tool for Windows called [BabelPad](https://babelstone.co.uk/Software/BabelPad.html) that I have found useful for reading files in one encoding and writing them in another, as well as for checking the encoding of a file.  I think all modern programmer's text editors should be able to save in UTF-8, but if you're working with old files they may need to be converted to UTF-8.

**Comment by miguelsousa** [comment] 2020-09-03 18:00
@astype if you use `#` to start a comment line I think you should be able to use `ä` or any non-ASCII characters on that line without a problem.

**Comment by josh-hadley** [comment] 2020-09-25 22:53
I'm going to assume this is resolved, and close the issue. Please re-open and comment if there's an issue in the AFDKO that needs to change.

**Closed by josh-hadley** 2020-09-25 22:53 UTC
